### ISSUE TITLE
Capybara

### ISSUE THREAD

**Issue by enricoperissinotto1** [jmopr/job-hunter#14]
/Users/studioomega/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- capybara-webkit (LoadError)
	from /Users/studioomega/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from applier.rb:2:in `<main>'

**Comment by mnandanpandya** [comment]
@enricoperissinotto1 Can you share steps to reproduce this error

**Comment by mohdhm** [comment]
@enricoperissinotto1 Did you properly install/compile the webkit?
