### ISSUE TITLE
Page not Rendering

### ISSUE THREAD

**Issue by boxboi1471** [jmopr/job-hunter#9]
After I fill in 

> **Enter job title or keywords**

> **Enter city, state or zip code**

> **Pages to inspect (not needed for angel site)** > I am using indeed, so i enter "1" to test

and Click "Find Jobs", No Jobs are displayed. The page refreshes and erases all entered information with no hits.

![job-hunter debug](https://cloud.githubusercontent.com/assets/23205809/19940009/72f37d28-a0e8-11e6-8ecd-ecabc277cc8c.png)

The debug output is:

```
Started GET "/search?utf8=%E2%9C%93&title=cyber+security&location=Los+angeles&pages=1                                                                                                       &indeed_scraper=1&commit=Find+Jobs" for 162.119.232.105 at 2016-11-02 10:27:54 -0700
Cannot render console from 162.119.232.105! Allowed networks: 127.0.0.1, ::1, 127.0.0                                                                                                       .0/127.255.255.255
Processing by JobsController#search as HTML
  Parameters: {"utf8"=>"✓", "title"=>"cyber security", "location"=>"Los angeles", "pa                                                                                                       ges"=>"1", "indeed_scraper"=>"1", "commit"=>"Find Jobs"}
  User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1                                                                                                         [["id", 2]]
Running via Spring preloader in process 8563
/var/lib/gems/2.3.0/gems/capybara-webkit-1.10.1/lib/capybara/webkit/server.rb:56:in `                                                                                                       parse_port': /var/lib/gems/2.3.0/gems/capybara-webkit-1.10.1/bin/webkit_server failed                                                                                                        to start. (Capybara::Webkit::ConnectionError)
        from /var/lib/gems/2.3.0/gems/capybara-webkit-1.10.1/lib/capybara/webkit/serv                                                                                                       er.rb:42:in `discover_port'
        from /var/lib/gems/2.3.0/gems/capybara-webkit-1.10.1/lib/capybara/webkit/serv                                                                                                       er.rb:26:in `start'
        from /var/lib/gems/2.3.0/gems/capybara-webkit-1.10.1/lib/capybara/webkit/conn                                                                                                       ection.rb:67:in `start_server'
        from /var/lib/gems/2.3.0/gems/capybara-webkit-1.10.1/lib/capybara/webkit/conn                                                                                                       ection.rb:17:in `initialize'
        from /var/lib/gems/2.3.0/gems/capybara-webkit-1.10.1/lib/capybara/webkit/driv                                                                                                       er.rb:16:in `new'
        from /var/lib/gems/2.3.0/gems/capybara-webkit-1.10.1/lib/capybara/webkit/driv                                                                                                       er.rb:16:in `initialize'
        from /var/lib/gems/2.3.0/gems/capybara-webkit-1.10.1/lib/capybara/webkit.rb:1                                                                                                       5:in `new'
        from /var/lib/gems/2.3.0/gems/capybara-webkit-1.10.1/lib/capybara/webkit.rb:1                                                                                                       5:in `block in <top (required)>'
        from /var/lib/gems/2.3.0/gems/capybara-2.7.0/lib/capybara/session.rb:85:in `d                                                                                                       river'
        from /var/lib/gems/2.3.0/gems/capybara-2.7.0/lib/capybara/session.rb:233:in `                                                                                                       visit'
        from /var/lib/gems/2.3.0/gems/capybara-2.7.0/lib/capybara/dsl.rb:52:in `block                                                                                                        (2 levels) in <module:DSL>'
        from scraper.rb:31:in `scrape'
        from scraper.rb:145:in `<top (required)>'
        from /var/lib/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/runner.rb:6                                                                                                       0:in `load'
        from /var/lib/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/runner.rb:6                                                                                                       0:in `<top (required)>'
        from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/depend                                                                                                       encies.rb:274:in `require'
        from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/depend                                                                                                       encies.rb:274:in `block in require'
        from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/depend                                                                                                       encies.rb:240:in `load_dependency'
        from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/depend                                                                                                       encies.rb:274:in `require'
        from /var/lib/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/commands_ta                                                                                                       sks.rb:123:in `require_command!'
        from /var/lib/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/commands_ta                                                                                                       sks.rb:90:in `runner'
        from /var/lib/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/commands_ta                                                                                                       sks.rb:39:in `run_command!'
        from /var/lib/gems/2.3.0/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<                                                                                                       top (required)>'
        from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/depend                                                                                                       encies.rb:274:in `require'
        from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/depend                                                                                                       encies.rb:274:in `block in require'
        from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/depend                                                                                                       encies.rb:240:in `load_dependency'
        from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/depend                                                                                                       encies.rb:274:in `require'
        from /home/default/Downloads/jobhunter/job-hunter/bin/rails:9:in `<top (requi                                                                                                       red)>'
        from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/depend                                                                                                       encies.rb:268:in `load'
        from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/depend                                                                                                       encies.rb:268:in `block in load'
        from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/depend                                                                                                       encies.rb:240:in `load_dependency'
        from /var/lib/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/depend                                                                                                       encies.rb:268:in `load'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
Redirected to http://47.153.228.238:3000/users/jobs
Completed 302 Found in 5247ms (ActiveRecord: 0.8ms)


Started GET "/users/jobs" for 162.119.232.105 at 2016-11-02 10:27:59 -0700
Cannot render console from 162.119.232.105! Allowed networks: 127.0.0.1, ::1, 127.0.0                                                                                                       .0/127.255.255.255
Processing by JobsController#index as HTML
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1                                                                                                         [["id", 2]]
   (0.8ms)  SELECT COUNT(*) FROM "jobs"
  Job Load (0.8ms)  SELECT  "jobs".* FROM "jobs"  ORDER BY "jobs"."id" ASC LIMIT 25 O                                                                                                       FFSET 0
  Rendered jobs/index.html.erb within layouts/application (20.3ms)
Completed 200 OK in 189ms (Views: 182.5ms | ActiveRecord: 2.1ms)
```

Any Suggestions?

**Comment by abunsen** [comment]
Hey @boxboi1471 looks like some of your debug output is missing, so we can't see the full error.

**Comment by ryantstone** [comment]
@boxboi1471  What OS is being used? If you're on Sierra capybara-webkit has some issues. [Link](https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#macos-sierra-1012)

**Comment by abunsen** [comment]
No response so closing this.
